FROM debian:latest

WORKDIR /home/test

RUN apt update && \
    apt install -y\
    libgirepository1.0-dev \
    libcairo2-dev \
    gir1.2-gtk-3.0 \
    libcanberra-gtk3-module \
    libgl1-mesa-glx \
    libegl1 \
    libxkbcommon-x11-0 \
    libxcb-cursor0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-shape0 \
    libxcb-xfixes0 \
    libxcb-xinerama0 \
    libxcb-sync1

